### ISSUE TITLE
GEM_HOME is set in my shell when tmuxinator runs

### ISSUE THREAD

**Issue by marcw** [tmuxinator/tmuxinator#776] opened 2020-05-28 07:30 UTC
**Describe the bug**

warning: I'm a complete ruby noob, but I've got bitten multiple times by this.

The `GEM_HOME` environment variable is set in my shell when tmuxinator runs. This creates various undesirable side effects when running Ruby scripts. 

**To Reproduce**

- Create the `~/.config/tmuxinator/foobar.yml` configuration file (see below)
- Create a `tm` executable file with content somewhere in your PATH.
```
#!/bin/zsh
tmuxinator start foobar
```
- Run `tm` in your shell.

**Expected behavior**

I would like tmuxinator to not set the `GEM_HOME` environment variable, so that it doesn't mess with any `gem install`. Or, alternatively, I would like my `gem install` not messed up when running inside tmuxinator.

**Environment**
 - tmuxinator Version: 1.1.5 
- tmux Version: 3.1
 - Ruby Version: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
 - OS: macOS Catalina

**Additional information**

Content of my tmuxinator configuration file:

```
# /Users/marc/.config/tmuxinator/foobar.yml

name: marc
root: ~/

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
startup_window: bf:root

windows:
  - dashboard:
      layout: main-vertical
      panes:
        - wtfutil

  - tools:
      layout: d4f0,178x45,0,0{89x45,0,0,9,88x45,90,0[88x22,90,0,14,88x22,90,23,15]}
      panes:
        - org ls 
        - 
        -

  - general:
      layout: even-horizontal
      panes:
        -
        -

  - bf:root:
      layout: even-horizontal
      root: "~/foo/bar"
      panes:
        -
        -
  - bf:private:
      layout: e703,178x48,0,0{89x48,0,0[89x24,0,0,16,89x23,0,25,18],88x48,90,0,17}
      root: ~/foo/bar
      panes:
        - 'cd baz'
        - 'cd baz'
        - 'cd baz'

  - bf:python:
      root: ~/foo/bar

  - bf:go:
      root: ~/foo/bar

  - bf:ruby:
      root: ~/foo/bar

```

**Comment by ethagnawl** [comment] 2020-05-30 02:44
Hi, @marcw.

I don't believe this is tmuxinator's doing, per se, but is possibly caused by some piece of the Ruby toolchain, which might _possibly_ be invoked when you run tmuxinator. (FWIW, I just attempted to simulate this on a MacBook running High Sierra and didn't see the issue.)

I'd still like to help you if I'm able, though. Could you do the following and confirm that `$GEM_HOME` is still being set unexpectedly? (This shouldn't have any negative effects, since you don't want this variable set, but be careful.)

```
unset GEM_HOME
tmuxinator list
echo $GEM_HOME
```

If the variable wasn't set, you could try starting your project to see if that makes a difference, but I can't imagine it would.

Also, you said you were running into issues with where things are being installed from within a tmux/inator session: You can control where `gem` install libraries and their dependencies using the `-i` flag. 

For example, until you address the undesired behavior, you could use: `gem install -i ./gem-install-test colorls` within tmux/inator sessions.

**Comment by marcw** [comment] 2020-06-02 07:50
Thank you very much for your help @ethagnawl. 

Here is the result.

```
Last login: Tue Jun  2 09:36:52 on ttys001
You have mail.
~|0|$ echo $GEM_HOME

~|0|$ unset GEM_HOME
~|0|$ tmuxinator list
tmuxinator projects:
blackfire
~|0|$ echo $GEM_HOME

~|0|$
```

I just realized I didn't specify the content of `$GEM_HOME`, so here it is:

```
# when inside a tmux session launched by tmuxinator
$ echo $GEM_HOME
/usr/local/Cellar/tmuxinator/1.1.5/libexec
```

**Comment by marcw** [comment] 2020-06-02 07:51
and now I understand:

```
$ cat `which tmuxinator`
#!/bin/bash
GEM_HOME="/usr/local/Cellar/tmuxinator/1.1.5/libexec" exec "/usr/local/Cellar/tmuxinator/1.1.5/libexec/bin/tmuxinator" "$@"
```

**Comment by ethagnawl** [comment] 2020-06-02 13:49
[It'd seem to be a Homebrew issue](https://github.com/Homebrew/homebrew-core/pull/44567/files#diff-8ab51bf324505887d3bc7d5f2fff4710R37). I don't use Homebrew and the "formula" is maintained by the Homebrew project. It might be worth opening an issue there, but I have no idea what the solution would look like.

I'm going to close this issue for now, but let me know if you think there's anything else worth discussing.

**Closed by ethagnawl** 2020-06-02 13:49 UTC

**Comment by marcw** [comment] 2020-06-02 15:05
Many thanks for your time.
