### ISSUE TITLE
mux open overwrites existing configuration file

### ISSUE THREAD

**Issue by mrsdizzie** [tmuxinator/tmuxinator#362] opened 2015-12-02 00:37 UTC
Having an issue where running 'mux open mysite' is silently overwriting an existing ~/.tmuxinator/mysite.yml file with the default content. It looks like the code is supposed to detect an existing file (good!) but isn't correctly my case.

ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
tmuxinator 0.7.0
Debian GNU/Linux 8.2 (jessie) (4.0.4-x86_64-linode57)

Also made a little screencast so you can see it overwriting an existing file:
 
 https://asciinema.org/a/90intjhjsdvr3qcqpxo4hd0l5

Hope this helps!

**Comment by ethagnawl** [comment] 2015-12-02 01:16
This a dupe of #355. The same bug was responsible for this behavior when using `mux new`, `mux edit` and `mux open`.

[The fix is in master](https://github.com/tmuxinator/tmuxinator/commit/dfde9284f3f060241de2cd34cdc55acfdff4b108) and there should be an updated Gem (0.7.1) released in the coming days.

**Closed by ethagnawl** 2015-12-02 01:16 UTC
