### ISSUE TITLE
tmux 3.2 has been released

### ISSUE THREAD

**Issue by jaspertandy** [tmuxinator/tmuxinator#814] opened 2021-04-14 13:01 UTC
**Describe the bug**
Using tmuxinator 2.0.2 with tmux 3.2 results in a version warning:

```
    WARNING: You are running tmuxinator with an unsupported version of tmux.
    Please consider using a supported version:
    (3.1c, 3.1b, 3.1a, 3.1, 3.0a, 3.0, 2.9a, 2.9, 2.8, 2.7, 2.6, 2.5, 2.4, 2.3, 2.2, 2.1, 2.0, 1.9, 1.8, 1.7, 1.6, 1.5)
```

**To Reproduce**
Install the latest version of tmux from homebrew on Mac (currently 3.2), and invoke any tmuxinator project.

**Expected behavior**
I would expect there to be no warning

**Environment**
 - tmuxinator Version: tmuxinator 2.0.2
- tmux Version: tmux 3.2
 - Ruby Version: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
 - OS: MacOS 11.2.3

**Comment by ethagnawl** [comment] 2021-04-14 13:16
This is a duplicate of #764. 

A new release which explicitly supports tmux 3.2 will be published shortly. In the meantime and going forward, you can use the `--suppress-tmux-version-warnings` flag when starting tmuxinator to bypass these warnings.

**Closed by ethagnawl** 2021-04-14 13:16 UTC

**Comment by jaspertandy** [comment] 2021-04-14 13:18
Ah sorry, I was searching for "3.2" in issues and didn't find that one.

**Comment by Shamaoke** [comment] 2021-04-14 15:09
> In the meantime and going forward, you can use the --suppress-tmux-version-warnings flag when starting tmuxinator to bypass these warnings.

    tmuxinator --suppress-tmux-version-warnings start basic
    ERROR: "tmuxinator help" was called with arguments ["--suppress-tmux-version-warnings", "start", "basic"]
    Usage: "tmuxinator help [COMMAND]"
    
_tmux 3.2_; _tmuxinator 2.0.2_

**Comment by jaspertandy** [comment] 2021-04-14 15:12
@Shamaoke ```tmuxinator start PROJECTNAME --suppress-tmux-version-warning=SUPPRESS-TMUX-VERSION-WARNING```

**Comment by Shamaoke** [comment] 2021-04-14 15:22
@jaspertandy That way it works, thanks.
