### ISSUE TITLE
Tmuxinator won't start

### ISSUE THREAD

**Issue by frdrcv** [tmuxinator/tmuxinator#500] opened 2017-01-24 19:39 UTC
Tmuxinator won't start with any command.
I just installed ubuntu 16.10 on my computer and reinstalled tmuxinator. I was using it before on Fedora 25 without any problem, but now, after installing the gem, I just can't start it. Every time I send tmuxinator, tmuxinator list or tmuxinator start personnel (which is a past yml file I was using), I get the following error message:
`/home/nrfrd/bin/tmuxinator:22:in '<main>': undefined method 'activate_bin_path' for Gem:Module (NoMethodError)`
I don't understand why the error message point to /home/nrfrd/bin/tmuxinator; there's no such file in my bin directory. Actually, the only file I know I have in my home related to tmuxinator are two .yml files in the .tmuxinator. I tried to reinstall tmuxinator, but I still get the same errors.

**Comment by ethagnawl** [comment] 2017-01-24 19:55
Hi, @frdrcv. 

Which version of tmuxinator/tmux/Ruby are you using? How are you installing tmuxinator? 

Also, have you seen [this](https://github.com/bundler/bundler/issues/4602) Bundler issue? It sounds like your problem _could_ be related.

**Comment by frdrcv** [comment] 2017-01-24 20:22
I'm using :
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
tmux 2.2
I can't tell which version of tmuxinator I'm using, as I get the error I named before - is there another way to get it?
I installed it with the command on the about.md on github, which is `gem install tmuxinator`

I don't really know about bundler; I'm not a programmer, so I don't really know how I could test it; do you have any recommandation?

**Comment by frdrcv** [comment] 2017-01-24 20:32
Actually, when I try to just exec bundler, I get an identical error as tmuxinator:
`/home/nrfrd/bin/bundler:22:in `<main>': undefined method `activate_bin_path' for Gem:Module (NoMethodError)`

**Comment by J3RN** [comment] 2017-01-24 21:20
@frdrcv Could you tell us the output of `gem --version` and `ruby --version`?

Also, did you have to use `sudo` to install? That may be causing issues if so.

Irrelevantly, this issue #500! 🎉

**Comment by Adriel-M** [comment] 2017-01-26 06:16
Having the same issue.

gem --version: 2.6.10
ruby --version: ruby 2.2.6p396 (2016-11-15 revision 56800) [amd64-freebsd11]

I installed from ports and via gem install. tmuxinator was working fine before a ruby update.

**Comment by ethagnawl** [comment] 2017-01-26 15:10
@Adriel-M Are you able to install/use other gems or does this only affect tmuxinator?

**Comment by Adriel-M** [comment] 2017-01-26 22:08
I don't use any other gems. Got anything specific for me to test out?

**Comment by ethagnawl** [comment] 2017-01-26 22:33
@Adriel-M Try, `gem install pry && pry`.

**Comment by Adriel-M** [comment] 2017-01-26 22:45
@ethagnawl pry worked for me.

**Comment by ethagnawl** [comment] 2017-01-27 00:35
@Adriel-M Yes, [due to a bug in Rubygems](https://github.com/tmuxinator/tmuxinator/issues/401). However, if you [enable shell completion](https://github.com/tmuxinator/tmuxinator#completion), `mux` [should work again](https://github.com/tmuxinator/tmuxinator#shorthand).

**Comment by ethagnawl** [comment] 2017-02-01 23:00
@frdrcv Are you still seeing this issue? If so - and this is admittedly a shot-in-the-dark - perhaps you could try upgrading RubyGems via `gem update --system` and reinstalling tmuxinator.

**Comment by gauthamchandra** [comment] 2017-02-15 15:25
I had the same issue recently and had the latest completion file aliasing `mux` to `tmuxinator` but I had an older version of tmuxinator. Installing the latest version via `gem install tmuxinator` fixed it. 👍

**Comment by ethagnawl** [comment] 2017-08-29 22:36
Are you still seeing this issue, @frdrcv?

**Comment by janemba** [comment] 2018-05-17 06:15
Hello,

I have the exact same issue. So I'll use this thread instead of opening a new one. Is it ok ?

So whatever command I type : `$ tmuxinator --help` `$ tmuxinator --version` `$ tmuxinator doctor` I don't get any output.

please find below some context :
```
$ ruby --version
ruby 2.4.3p205 (2017-12-14 revision 61247) [armv7l-linux-eabi]

$ gem --version
2.7.6

$ tmux -V
2.1
```

Do you how to debug this ?

Please let me know if you need further details.

**Comment by ethagnawl** [comment] 2018-05-17 15:03
Hi, @janemba.

A few thoughts/questions:

- It looks like you're running this on an ARM device. I've never tried using tmuxinator on an ARM device and don't think I've heard of anyone else doing it either. It's quite possible that there are assumptions about architecture/platform baked into the library or one of its dependencies. When I have some time, I will try to install tmux/tmuxinator on one of my Pis and report back.

- I'd recommend debugging either via `bundle open tmuxinator` or by cloning this repository.

**Comment by janemba** [comment] 2018-05-17 17:20
Hi @ethagnawl,

Yes I'm using an ARM device. I will try the `bundle` command and let you know the result.

Thx

**Comment by janemba** [comment] 2018-05-22 06:34
Hi @ethagnawl ,

Sorry for the late answer. I try the `bundle` command on tmuxinator git repository but I didn't how to debug things.

So, I tried again to execute `tmuxinator` from command-line with `strace`. I noticed that all the call to `ioctl` function failed. That call is made just after `open` function against ruby files is called (same file descriptor).

The  error from `ioctl` call is `-1 ENOTTY (Inappropriate ioctl for device)` (`ioctl` uses `TCGETS` as request).

So I've made a check for this error and I discover this :
**https://stackoverflow.com/questions/34495708/linux-kernel-module-ioctl-usage-returns-enotty**
```
When 32bit application is run on 64bit OS, it uses compat_ioctl syscall instead of unlocked_ioctl one for perform ioctl command. The reason of special syscall is that size of ioctl argument may differ for 64bit and 32bit applications.

So you need to implement .compat_ioctl file operation.
```
I forgot to mention but my ARM box use a 32 bit CPU.

I checked my ruby installation in case. And `irb` seems to work well. `tmux` works fine too.

So is it possible that some 64 bit library or something else is hiding in `tmuxinator` ?

**Comment by ethagnawl** [comment] 2018-05-23 18:48
@janemba That's some nice sleuthing! I really need to revisit `strace` ...

Anyways, in order to debug, I'd recommend cloning the repository and then trying to run the tests (follow README) and/or putting [this](https://gist.github.com/ethagnawl/22158d50980b5ac6c861a470460cfaca) script into the repo's bin directory, running `chmod +x ./bin/console`, running it (`./bin/console`) and poking around (e.g. `Tmuxinator::Cli::start name: "foo"`). (I will be adding the console script to the project.) Hopefully some errors will present themselves and we can progress from there.

Also, FWIW, I installed tmuxinator on a 32-bit/i386 machine this morning and didn't have any issues.

**Comment by janemba** [comment] 2018-05-24 06:49
@ethagnawl 

I didn't find any `tests` section in the `README.md` file. So I just did the test with `./bin/console`.

When I execute the script I don't have any output, I guess `irb` is not executed :
```
$ ./bin/console

```

The cursor stay here but the process is not frozen (running at 100%).

So I run strace command against `./bin/console`.  I don't know if it can help.

[log.txt](https://github.com/tmuxinator/tmuxinator/files/2034118/log.txt)

**Comment by ethagnawl** [comment] 2018-05-24 13:57
@janemba Sorry! I thought the test instructions were in README, but they're in CONTRIBUTING. Anyways, it should just be: `bundle install && bundle exec rake test`

**Comment by janemba** [comment] 2018-05-27 09:52
Hi @ethagnawl,

So I tried the bundle command and I got this:
```
$ bundle exec rake test --trace
** Invoke test (first_time)
** Invoke spec (first_time)
** Execute spec
/usr/bin/ruby -I/home/janemba/.vendor/bundle/ruby/2.4.0/gems/rspec-core-3.7.1/lib:/home/janemba/.vendor/bundle/ruby/2.4.0/gems/rspec-support-3.7.1/lib /home/janemba/.vendor/bundle/ruby/2.4.0/gems/rspec-core-3.7.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
```

(I did the bundle install before).

So then, nothing happens and the ruby process is at 100%.

**Comment by ethagnawl** [comment] 2018-06-01 16:23
@janemba Hmm... that's not much help.

Maybe we should take a step back first and ensure that tmuxinator's expected output is even useful on your machine. Try downloading [this](https://gist.github.com/ethagnawl/58f4cd6dbbd0440be4cce8a0261356e1) script, changing `YOUR_PROJECT_DIRECTORY` to some directory on your machine, making it executable (`chmod +x debug-tmuxinator.sh`) and running it (`./debug-tmuxinator.sh`).

**Comment by janemba** [comment] 2018-06-03 09:30
Hi @ethagnawl,

I tried the script and I did 3 screenshots. So when executing the script I got some output (there is a fortune from my shell) and then I did exit and I got some panes and I did again
![tmux_1](https://user-images.githubusercontent.com/12960990/40885164-3dc702c0-6732-11e8-8fc0-d9081ff8f9b1.png)
![tmux_2](https://user-images.githubusercontent.com/12960990/40885165-3dfbbdd0-6732-11e8-82fb-594d9848c317.png)
![tmux_3](https://user-images.githubusercontent.com/12960990/40885166-3e2ef344-6732-11e8-8482-eb9180ae6647.png)

**Comment by ethagnawl** [comment] 2018-06-03 21:41
@janemba Okay. Well, at least we now know the tmux side of things will work. 

Unfortunately, I was able to get my hands on a 32-bit ARM device (ARMV7 via Scaleway) and was able to install/run tmuxinator and run the test suite without any issues.

![screenshot 2018-06-03 17 36 39](https://user-images.githubusercontent.com/289949/40891536-21a4a4e4-6755-11e8-9693-c7be4f9829c6.png)

So, I'm pretty much out of ideas on how else to debug your issue at the moment. I'll chew on it and follow up if I think of anything.

**Comment by janemba** [comment] 2018-06-05 07:36
@ethagnawl 

So maybe the issue is not related to tmuxinator. So I will check for ruby and others stuff instead.

Thank you.

**Comment by ethagnawl** [comment] 2018-06-08 03:36
@janemba I'm going to close this for now. If you wind up uncovering a problem with tmuxinator, please open a new issue and we can proceed from there.

**Closed by ethagnawl** 2018-06-08 03:36 UTC
Labels: Bundler/RubyGems

**Comment by lhyundeadsoul** [comment] 2020-03-30 09:28
> I had the same issue recently and had the latest completion file aliasing `mux` to `tmuxinator` but I had an older version of tmuxinator. Installing the latest version via `gem install tmuxinator` fixed it. 👍

this work for me!!!
