### ISSUE TITLE
tmuxinator 0.9.0-2 panels render in wrong place / size

### ISSUE THREAD

**Issue by mrturtledev** [tmuxinator/tmuxinator#557] opened 2017-09-21 12:17 UTC
When using tmux/tmuxinator I can't get the tmuxinator windows to load in the correct place at the correct size. I ran tmux and configured the panels how I wanted them, detached and ran tmux list-windows -t 0 to get the layout. I copied the relevant bit of the layout to a tmuxinator config called recon, but they are out of position when starting that tmuxinator profile.

Kali rolling
tmux                                      2.6~rc3-1                            amd64        
tmuxinator                                0.9.0-2                              all          

list-windows 0: bash* (4 panes) [317x85] [layout 2fb3,317x85,0,0{203x85,0,0[203x21,0,0{97x21,0,0,0,105x21,98,0,4},203x63,0,22,3],113x85,204,0,1}] @0 (active)

list-windows   recon* (4 panes) [317x85] [layout 87e8,317x85,0,0{196x85,0,0[196x33,0,0{121x33,0,0,9,74x33,122,0,10},196x51,0,34,11],120x85,197,0,12}] @2 (active)

layout from  tmuxinator config                 2fb3,317x85,0,0{203x85,0,0[203x21,0,0{97x21,0,0,0,105x21,98,0,4},203x63,0,22,3],113x85,204,0,1}

The layout from the recon config matches the layout from list-windows -t 0 where I "templated" it from. However the list-windows -t recon after running tmuxinator start recon, shows a different value.

Here is the recon profile
# ~/.tmuxinator/recon.yml

```
name: recon
root: ~/

windows:
   recon:
      layout: 2fb3,317x85,0,0{203x85,0,0[203x21,0,0{97x21,0,0,0,105x21,98,0,4},203x63,0,22,3],113x85,204,0,1}
      root: /usr/src/git/
      panes:
        - screenfetch
        - date
        - cd ./WhatWeb/ && reset
        - date
```

This is all done in the same SSH session, same size window, etc.

**Comment by ethagnawl** [comment] 2017-09-21 15:08
Hey, @mrturtledev.

I'll need to circle back when I have some time, but when I try using your layout I'm met with `undefined method 'keys' for #<Array:0x00000002a9f6a8>`.

In the meantime, perhaps you could try upgrading to the latest tmuxinator (0.10.0) to see if that helps?

(Possibly related to the issue reported in #552.)

**Comment by mrturtledev** [comment] 2017-09-22 08:34
Sorry, the config file went a bit wrong when I copied it.
`
 ~/.tmuxinator/recon.yml

name: recon
root: ~/
tmux_options: -vvv
windows:
  - recon:
      layout: 2fb3,317x85,0,0{203x85,0,0[203x21,0,0{97x21,0,0,0,105x21,98,0,4},203x63,0,22,3],113x85,204,0,1}
      root: /usr/src/git/
      panes:
        - screenfetch
        - date
        - cd ./WhatWeb/ && reset
        - date

`

Tested on tmuxinator 0.10 with the same issue.

**Comment by sethdeckard** [comment] 2017-10-24 14:52
I'm running into basically the same issue while setting up a new machine using tmuxinator 0.10 and tmux 2.6.

I run `list-windows` on my current session and I get the following layout value: 

`00c3,238x118,0,0[239x94,0,0{120x94,0,0,0,118x94,121,0,1},239x24,0,95,2]`

When I set that as my layout in my config yml and restart the session it changes the heigh of the lower pane to 50 (was 24). Running a `list-windows` again shows the following layout value:

`e4c5,238x118,0,0[239x68,0,0{120x68,0,0,0,118x68,121,0,1},239x50,0,69,2]`

I am not getting any error messages from tmux that the layout is invalid.

**Comment by ryansch** [comment] 2017-11-16 17:14
I'm seeing the same behavior as @sethdeckard.

**Comment by eriktux** [comment] 2017-11-29 06:11
Also having the same issue here.

Arch Linux / rolling
tmux 2.6
tmuxinator 0.10.0

I did a full system upgrade yesterday, and since then, the layout I was using on a daily basis, is now broken.

**Comment by ctnieves** [comment] 2018-06-01 20:38
Having a similar issue here.  

Kali Linux
tmux 2.7
tmuxinator 0.11.2

**Comment by GregPK** [comment] 2019-10-30 12:24
@eriktux @ctnieves Does this still exist in the latest version? Did you manage to fix it somehow?

**Comment by ethagnawl** [comment] 2019-10-30 13:48
Maybe this issue is related to #651?

**Comment by ethagnawl** [comment] 2020-05-17 18:14
Appears to be a duplicate of #651. Feel free to reopen if there's more to discuss.

**Closed by ethagnawl** 2020-05-17 18:14 UTC
