### ISSUE TITLE
tmuxinator open [project] always overwrites existing file

### ISSUE THREAD

**Issue by endline** [tmuxinator/tmuxinator#363] opened 2015-12-14 07:12 UTC
as described in title. when calling `tmuxinator open [existing_project]` to edit, the contents of the file are always initialised the same as if calling `new`.

**Comment by KevinSjoberg** [comment] 2015-12-14 10:26
I'm encountering the same problem.

**Comment by ethagnawl** [comment] 2015-12-14 11:57
Which version of Tmuxinator are you using? If it's 0.7.0, then this is a 
dupe of #355. The same bug was responsible for this behavior when using mux 
new, mux edit and mux open.

The fix is in master and there should be an updated Gem (0.7.1) released in 
the coming days.

**Comment by KevinSjoberg** [comment] 2015-12-14 12:42
@ethagnawl I'm suing `tmuxinator 0.7.0`. Good to know a fix is already in place. :+1:

**Comment by adamstrickland** [comment] 2015-12-14 14:58
I'll release the gem later today

**Closed** 2015-12-14 15:37 UTC
Labels: duplicate

**Comment by adamstrickland** [comment] 2015-12-14 16:17
@endline @KevinSjoberg 0.7.1 has been released to [rubygems](https://rubygems.org/gems/tmuxinator)

**Comment by KevinSjoberg** [comment] 2015-12-14 18:06
Cheers @adamstrickland!

**Comment by endline** [comment] 2015-12-14 20:53
awesome. cheers @adamstrickland
