### ISSUE TITLE
Global configuration?

### ISSUE THREAD

**Issue by axelson** [tmuxinator/tmuxinator#223] opened 2014-04-21 20:45 UTC
Is it possible to make global configuration for tmuxinator? I'd like to be able to easily change the tmux executable command (`tmux_command`) across all of my 11 tmuxinator projects without needing to edit all their individual files.

In this particular case I want `tmux` to call `tmux -2` for 256 color support.

**Comment by Criten** [comment] 2015-05-20 18:19
+1

**Comment by J3RN** [comment] 2016-06-13 15:50
Sorry for just now getting around to reviewing this issue. As for this, I'd lean towards putting your Tmux configuration in your `.tmux.conf` file. For the 256-color example, that would look like:
```
set -g default-terminal "screen-256color"
```

If someone has an example of a Tmux configuration option that cannot be specified in Tmux's configuration file, please post it below and I'll look into implementing something.

**Comment by ethagnawl** [comment] 2020-05-08 01:32
Closing as a duplicate of #253. Feel free to reopen if there's anything substantially different between the two or worth discussing.

**Closed by ethagnawl** 2020-05-08 01:32 UTC
