### ISSUE TITLE
mux doesn't works

### ISSUE THREAD

**Issue by mMontu** [tmuxinator/tmuxinator#412] opened 2016-04-27 14:00 UTC
After installing tmuxinator on a new machine (and building the latest version of tmux) I notice that `tmuxinator` runs normally, but `mux` doesn't. Issuing `$ tmuxinator` returns the help message, and `$ tmuxinator doctor` says everything is fine. But both `$ mux`  and `$ mux doctor` print nothing and return immediately.

The binaries have slight different sizes:

    ll /usr/bin/ | grep mux
    -rwxr-xr-x   1 root   root     463 Apr 27 10:48 mux
    -rwxr-xr-x   1 root   root     470 Apr 27 10:48 tmuxinator

I've tried re-installing it, but nothing changes. Any ideas on how to debug this?

**Comment by adamstrickland** [comment] 2016-04-27 14:15
Duplicate of #401

**Closed** 2016-04-27 14:17 UTC
Labels: duplicate
