### ISSUE TITLE
LoadError with Ruby 2.3.0

### ISSUE THREAD

**Issue by JamesYuan** [tmuxinator/tmuxinator#434] opened 2016-07-07 07:52 UTC
After `gem pristine tmuxinator`,

$ rvm list

rvm rubies

   ruby-1.9.3-p551 [ x86_64 ]
   ruby-2.2.1 [ x86_64 ]
=* ruby-2.3.0 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
$ mux
/usr/local/bin/mux:23:in `load': cannot load such file -- /Users/jyuan/.rvm/gems/ruby-2.3.0/gems/tmuxinator-0.8.1/bin/mux (LoadError)
	from /usr/local/bin/mux:23:in `<main>'

Please help.

Thanks,
James.

**Comment by ethagnawl** [comment] 2016-07-07 12:54
This appears to be a duplicate of #401.

**Closed by ethagnawl** 2016-07-07 12:54 UTC
Labels: duplicate
