### ISSUE TITLE
Can not create more than two panes in a window. It results in parse error.

### ISSUE THREAD

**Issue by aashudwivedi** [tmuxinator/tmuxinator#477] opened 2016-10-18 13:05 UTC
I am not able to create a window with more than two panes. 

only adding a new pane to the default configuration results in a error saying : `Failed to parse config file. Please check your formatting.`

Here is my config file : 

`# ~/.tmuxinator/test.yml

name: test
root: ~/

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: editor

# Specitifes (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

# Runs after everything. Use it to attach to tmux with custom options etc.
# post: tmux -CC attach -t test

windows:
  - editor:
      layout: main-vertical
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - vim
        - guard
        - ls
  - server: bundle exec rails s
  - logs: tail -f log/development.log
`

**Comment by ethagnawl** [comment] 2016-10-18 14:20
@aashudwivedi This appears to be a duplicate of #478. Please re-open if not.

**Closed by ethagnawl** 2016-10-18 14:20 UTC
