### ISSUE TITLE
DEPRECATION: You are running tmuxinator with an unsupported version of tmux

### ISSUE THREAD

**Issue by maksimr** [tmuxinator/tmuxinator#609] opened 2018-04-02 08:39 UTC
In the latest version of **tmux** command `tmux -V` returns `master`
https://github.com/tmux/tmux/blob/919f55ac4a927712e463d8c59bfebc91d50058e2/CHANGES#L1

so now tmuxinator throws an error about unsupported version 
```
DEPRECATION: You are running tmuxinator with an unsupported version of tmux.
    Please consider using a supported version:
    (1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6)
```

tmuxinator 0.11.0
tmux master
MacOS

Thanks!

**Comment by ethagnawl** [comment] 2018-04-03 16:49
Hi, @maksimr.

Based on the information you've provided, the warning appears to be working as intended. AFAIK, tmux 2.7 hasn't been released yet, so I'm guessing you've built the RC from the master branch. Once 2.7 is minted and you either build from the release tarball or install via a package manager,  `tmux -V` will print "tmux 2.7". (Apologies if I'm stating the obvious, but I understand how the behavior you're seeing could be confusing.)

Once 2.7 has been released and tested against (and any issues have been addressed), it will be added to tmuxinator's range of supported versions. tmuxinator only explicitly supports the versions of tmux included in the range shown above and anything outside of that range (lower _or_ higher) is, technically, "unsupported". (If you're interested in the rationale, see [this](https://github.com/tmuxinator/tmuxinator/pull/545) conversation and the conversations it links to.)

I'm going to close this issue, but feel free to re-open and continue the conversation if I've misunderstood.

P.S. You may want to keep an eye on [this issue](https://github.com/tmuxinator/tmuxinator/issues/583) and consider submitting a PR if you want to continue using bleeding edge tmux and don't want to see the deprecation warning.

**Closed by ethagnawl** 2018-04-03 16:49 UTC

**Comment by maksimr** [comment] 2018-04-03 19:44
Thanks for reply,

> 'm guessing you've built the RC from the master branc

Unfortunately no, I got this version after run 'brew upgrade tmux' do it looks like master is a stable version...(in brew)

**Comment by ethagnawl** [comment] 2018-04-03 21:16
I haven't used homebrew in many years, so I can't speak to how it should/n't work, but that behavior is surprising. The [tmux homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/tmux.rb#L4) appears to have v2.6 hardcoded:

```
class Tmux < Formula
  desc "Terminal multiplexer"
  homepage "https://tmux.github.io/"
  url "https://github.com/tmux/tmux/releases/download/2.6/tmux-2.6.tar.gz"
```

Either way, I'm of the opinion that (given my comment above) tmuxinator is behaving as is expected.

**Comment by ethagnawl** [comment] 2018-04-16 19:25
@maksimr tmuxinator v0.11.1 has been released. After upgrading, you should no longer see a deprecation warning when using tmux v2.7.

**Comment by maksimr** [comment] 2018-04-16 19:27
@ethagnawl Thanks! 👍

**Comment by urbainvaes** [comment] 2024-02-23 10:31
Hi. I often have the same issue after updating tmux on Archlinux. I think it would be convenient to make this warning a bit more discrete, so that it's not in the way.

**Comment by mMontu** [comment] 2024-08-20 08:52
Hi, I got the same issue.

After the changes on https://github.com/tmuxinator/tmuxinator/pull/659 , it is possible to disable the warnings:

    mux start <project> --suppress-tmux-version-warning
