### ISSUE TITLE
mux new <name> erase existing project

### ISSUE THREAD

**Issue by nicolas33** [tmuxinator/tmuxinator#355] opened 2015-11-14 07:13 UTC
It's unexpected to erase existing projects. It should give an error or fallback to edit mode.
v0.7.0

**Comment by ethagnawl** [comment] 2015-11-14 17:51
I can also confirm that this broke when upgrading from 0.6.11 to 0.7.0.

**Comment by ethagnawl** [comment] 2015-11-14 22:02
Should be resolved by fix for #354.

**Comment by adamstrickland** [comment] 2015-11-23 23:31
Closing as duplicate of https://github.com/tmuxinator/tmuxinator/issues/354

**Closed by adamstrickland** 2015-11-23 23:32 UTC
